[package]
name = "MongoTurbo"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
mongodb = "2.8.2"
tokio = { version = "1", features = ["full"] }
dashmap = "5.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
chrono = "0.4"